import streamlit as st
from openai import OpenAI
import json
from streamlit_ace import st_ace
import pandas as pd

st.set_page_config(page_title="FlashForge AI ⚡", page_icon="⚡", layout="wide")
st.title("⚡ FlashForge AI")
st.markdown("**AI-Powered Solidity Flash Loan & Arbitrage Studio** – Deploy in < 5 min")

# ====================== SESSION STATE ======================
if "contract_code" not in st.session_state:
    st.session_state.contract_code = ""
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "current_template" not in st.session_state:
    st.session_state.current_template = None

# ====================== SIDEBAR ======================
with st.sidebar:
    st.image("https://raw.githubusercontent.com/user-attachments/FlashForge-Logo.png", width=200)  # optional
    st.title("Navigation")
    page = st.radio("Go to",
                    ["📚 Template Library",
                     "⚡ Flash Loan Wizard (Main)",
                     "🛠 Custom AI Builder",
                     "📜 My Contracts"])
   
    st.divider()
    st.caption("Connected Chain")
    chain = st.selectbox("Chain", ["Ethereum", "Arbitrum", "Base", "Optimism", "Polygon"], index=1)
   
    st.divider()
    st.markdown("**API Settings**")
    api_provider = st.radio("LLM Provider", ["xAI Grok (recommended)", "OpenAI"])
    if api_provider == "xAI Grok (recommended)":
        client = OpenAI(api_key=st.secrets["XAI_API_KEY"], base_url="https://api.x.ai/v1")
        model_name = "grok-2-latest"
    else:
        client = OpenAI(api_key=st.secrets.get("OPENAI_API_KEY"))
        model_name = "gpt-4o"

# ====================== TEMPLATES (hardcoded library) ======================
TEMPLATES = {
    "Simple Aave V3 Flash Loan Arbitrage": {
        "description": "Flash loan USDC → Buy WBTC on Uniswap V3 → Sell on Sushiswap → Repay",
        "code": """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
import "@aave/core-v3/contracts/flashloan/base/FlashLoanSimpleReceiverBase.sol";
import "@uniswap/v3-periphery/contracts/interfaces/ISwapRouter.sol";

contract FlashArbitrage is FlashLoanSimpleReceiverBase {
    ISwapRouter public immutable uniswapRouter;
    address public immutable wbtc;
    address public immutable usdc;
    // ... constructor & executeOperation logic generated by AI
    function startArbitrage(uint256 amount) external {
        POOL.flashLoanSimple(address(this), usdc, amount, "");
    }
}"""
    },
    "Balancer Batch Flash Loan + LP Add": {
        "description": "Batch flash loan → Triangular arbitrage → Add liquidity to Balancer pool",
        "code": "// Full template code here..."
    }
}

# ====================== MAIN PAGES ======================
if page == "📚 Template Library":
    st.header("Template Library – Quick Deploy")
    cols = st.columns(3)
    for i, (name, data) in enumerate(TEMPLATES.items()):
        with cols[i % 3]:
            with st.expander(f"**{name}**", expanded=True):
                st.write(data["description"])
                if st.button("Quick Deploy →", key=name):
                    st.session_state.contract_code = data["code"]
                    st.switch_page("app.py")  # refresh to show in editor
                st.button("Load into Builder", key=f"load_{i}")

elif page == "⚡ Flash Loan Wizard (Main)":
    st.header("⚡ Flash Loan Arbitrage Wizard")
   
    col1, col2 = st.columns([1, 2])
    with col1:
        st.subheader("1. Provider & Loan")
        provider = st.selectbox("Flash Loan Provider",
                                ["Aave V3 (0.09%)", "Uniswap V3 Flash Swap (0%)", "Balancer V2", "Morpho"])
        asset = st.selectbox("Asset", ["USDC", "WETH", "WBTC", "DAI"])
        amount = st.number_input("Loan Amount", value=100_000, step=10_000)
       
        st.subheader("2. Describe Your Strategy")
        user_prompt = st.text_area("Natural language (the more detailed, the better)",
                                   value="Flash loan 100k USDC from Aave on Arbitrum, buy WBTC on Uniswap V3 0.3% pool, sell WBTC on Sushiswap, add 50% of profit as liquidity to USDC-WBTC pool on Uniswap V3, repay loan with 0.1% slippage tolerance.",
                                   height=150)
   
    with col2:
        st.subheader("3. Generate Contract")
        if st.button("🚀 AI → Generate Full Solidity Contract", type="primary", use_container_width=True):
            with st.spinner("Grok is writing production-ready Solidity..."):
                system_prompt = """You are an expert Solidity engineer specialized in flash-loan arbitrage.
                Generate a complete, audited, gas-optimized Solidity 0.8.28 contract.
                - Use correct Aave V3 / Uniswap V3 / Balancer interfaces
                - Include executeOperation, startArbitrage, reentrancy guard, pausable
                - Add detailed comments and events
                - Handle slippage, deadlines, profit calculation
                - Follow the exact user strategy described below."""
               
                response = client.chat.completions.create(
                    model=model_name,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": f"Chain: {chain}\nProvider: {provider}\nAsset: {asset}\nAmount: {amount}\nStrategy: {user_prompt}"}
                    ],
                    temperature=0.2,
                    max_tokens=4000
                )
                generated_code = response.choices[0].message.content
                st.session_state.contract_code = generated_code
                st.success("✅ Contract generated!")

        # Live preview
        if st.session_state.contract_code:
            st.subheader("📄 Generated Contract")
            edited_code = st_ace(
                value=st.session_state.contract_code,
                language="solidity",
                theme="monokai",
                height=600,
                font_size=14,
                show_gutter=True,
                wrap=True,
                key="ace_editor"
            )
            st.session_state.contract_code = edited_code

            col_a, col_b, col_c = st.columns(3)
            with col_a:
                if st.button("📋 Copy to Clipboard"):
                    st.code(edited_code, language="solidity")
                    st.toast("Copied!")
            with col_b:
                st.download_button("⬇️ Download .sol", edited_code, file_name="FlashArbitrage.sol")
            with col_c:
                st.button("🔥 Test on Fork (Tenderly simulation)", disabled=True)  # placeholder

elif page == "🛠 Custom AI Builder":
    st.header("🛠 Custom AI Builder")
    st.info("Tell the AI exactly what you want – it will build any Solidity contract.")
    custom_prompt = st.text_area("Describe your full contract (flash loan + any logic)", height=200)
    if st.button("Generate Custom Contract"):
        # Same LLM call as above but with custom_prompt
        st.session_state.contract_code = "/* AI will generate here */"
        st.rerun()

elif page == "📜 My Contracts":
    st.header("My Contracts")
    st.info("All your generated contracts are saved in session. Deploy them on Remix or Foundry.")
    if st.session_state.contract_code:
        st.code(st.session_state.contract_code, language="solidity")

# ====================== AI CO-PILOT CHAT (always visible) ======================
st.divider()
st.subheader("🤖 AI Co-Pilot Chat")
for msg in st.session_state.chat_history:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

if prompt := st.chat_input("Ask anything about your contract, gas optimization, security, etc."):
    st.session_state.chat_history.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)
   
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            response = client.chat.completions.create(
                model=model_name,
                messages=[{"role": m["role"], "content": m["content"]} for m in st.session_state.chat_history],
                temperature=0.7
            )
            answer = response.choices[0].message.content
            st.markdown(answer)
            st.session_state.chat_history.append({"role": "assistant", "content": answer})

# Footer
st.caption("FlashForge AI © 2026 | Built for share.streamlit.io | One-click deploy from GitHub") 
